### ISSUE TITLE
Refactor `GET` to `POST`

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/rest.bitcoin.com#49]
Any REST v1 endpoint which currently accepts an array of values should be ported from a `GET` to a `POST` and have the array passed in the POST body. We should also add pagination for up to 100 items per page instead of the current 20.

### Address

* ~~[address/details](https://rest.bitcoin.com/#/address/details)~~
* ~~[address/utxo](https://rest.bitcoin.com/#/address/utxo)~~
* ~~[address/unconfirmed](https://rest.bitcoin.com/#/address/unconfirmed)~~
* ~~[address/transactions](https://rest.bitcoin.com/#/address/transactions)~~

### Blockchain

* [blockchain/getBlockHash](https://rest.bitcoin.com/#/blockchain/getBlockHash)
* ~~[blockchain/getBlockHeader](https://rest.bitcoin.com/#/blockchain/getBlockHeader)~~
* [blockchain/getMempoolAncestors](https://rest.bitcoin.com/#/blockchain/getMempoolAncestors)
* [blockchain/getMempoolDescendants](https://rest.bitcoin.com/#/blockchain/getMempoolDescendants)
* ~~[blockchain/getMempoolEntry](https://rest.bitcoin.com/#/blockchain/getMempoolEntry)~~
* ~~/blockchain/getTxOutProof~~
* ~~/blockchain/verifyTxOutProof~~

### RawTransactions

* [rawtransactions/decodeRawTransaction](https://rest.bitcoin.com/#/rawtransactions/decodeRawTransaction)
* [rawtransactions/decodeScript](https://rest.bitcoin.com/#/rawtransactions/decodeScript)
* [rawtransactions/getRawTransaction](https://rest.bitcoin.com/#/rawtransactions/getRawTransaction)
* [rawtransactions/sendRawTransaction](https://rest.bitcoin.com/#/rawtransactions/sendRawTransaction)

### Transaction

* ~~[transaction/transactionDetails](https://rest.bitcoin.com/#/transaction/transactionDetails)~~

### Util

* ~~util/validateAddress~~

**Comment by cgcardona** [comment]
> Or do we let the user pass in any arbitrary sized POST body, but we paginate the output with 100 results per page?

That. If a response has 300 items we want the user to be able to paginate through them 100 at a time.

I'm not sure of a js pagination lib. I'm sure there's something on npm.

**Comment by christroutner** [comment]
@SpendBCH and I had a great conversation today about the specifics of the implementation of this issue. Below is the short version of what we talked about.

### Bug Analysis
I analyzed the `/address/details` and `/address/utxo` outputs of the current V1 implementation with different kinds of inputs, and compared it to the PR that caused a bug in rest.bitcoin.com last week.

**/address/details**
- single address not in an array `bchtest:xxxx`
  - V1 results in a single object output `{}` 
  - V2 prototype in an array containing a single object. `[{}]` *(this broke V1)*
- single address in an array as input `[bchtest:xxxx]` 
  - V1 results in an array containing a single object. `[{}]`
- multiple addresses in an array `[bchtest:xxxx, bchtest:yyyy]`
  - V1 results in an array of objects as output. `[{}, {}, ... {}]`

**/address/utxo**
- single address not in an array `bchtest:xxxx` 
  - V1 results in a single array with utxo objects `[{utxo1}, {utxo2}, ... {utxon}]` 
  - V2 prototype results in a double array of objects as output: `[[{utxo1}, {utxo2}, ... {utxon}]]` *(this broke V1)*
- single address in an array as input `[bchtest:xxxx]` 
  - V1 results in a double array of objects as output: `[[{utxo1}, {utxo2}, ... {utxon}]]`
- multiple address in an array `[bchtest:xxxx, bchtest:yyyy]`
  - V1 results in a double array of objects as output `[[{utxo1}, {utxo2}, ... {utxon}],[{utxo1}, {utxo2}, ... {utxon}]]`

Based on the above analysis, I assume that the proper output for a POST call should be:
- `/address/details` should output an array of objects: `[{}, {}, ... {}]`
- `/address/utxo` should output an array of arrays, containing utxo objects: `[[{utxo1}, {utxo2}, ... {utxon}],[{utxo1}, {utxo2}, ... {utxon}]]`

### Querying large datasets RESTfully
I did some research on the etiquette of GET and POST in REST as well. The V1 implementation uses GET calls and puts all the addresses in the URI. This has limitations with data sizes, as the URI can only be 2kB for many implementations. It also looks extremely messy.

The solution is to put this data into a body. But including a body with a GET call is considered improper REST behavior. The easy solution is to switch to POST in order to 'correctly' pass data in a body.
According to [this Stack Overflow thread](https://stackoverflow.com/questions/978061/http-get-with-request-body), this bit of nuance between GET, POST, and 'proper' REST usage has been an unanswered question for the better part of a decade.

[This article](https://evertpot.com/dropbox-post-api/) lays out what has been widely adopted as the 'best' implementation which uses a POST call to generate a report. The user then GETs the report. That would require a database, which rest.bitcoin.com currently does not use. It would also require a lot of overhead in terms of development.

@SpendBCH and I reached the conclusion that switching from GET to POST, strikes the best balance between ease of implementation and 'proper' REST etiquette. 

### The GUI
The downside of switching from GET to POST is that it effects the GUI presented at https://rest.bitcoin.com. The current V1 implementation presents the user with a succinct curl command as well as a URL that is easy to copy and paste.

POST calls with a data body are much longer and uglier in a curl call. I'm not totally positive on this, but I don't think they can be implemented as a URL either.

A solution to this would be to follow a similar REST pattern as the `/user` endpoint in [this koa boilerplate](https://github.com/christroutner/babel-free-koa2-api-boilerplate/blob/master/src/modules/users/controller.js):
- GET calls can be used to request a single address, maintaining current implementation and giving the user a nice GUI.
- POST calls can be used for large, single payloads or multiple addresses.

At this point in the refactor, it wouldn't be a great deal of effort to make both GET and POST endpoints. We'd really just be preserving the existing behavior with GET calls.

**Comment by SpendBCH** [comment]
Sounds good @christroutner 
Personally I favor using post as it is only one endpoint and seems more intuitive for a user to understand without reading through docs.

**Comment by christroutner** [comment]
The Address endpoints have been refactored to have both POST and GET endpoints. GET is reserved for single entities, and POST is reserved for batch entities.

**Comment by cgcardona** [comment]
V2 is now live and we have a single/bulk pattern in place. Closing.
